version: "3.9"
services:
  decoder:
    build:
      context: ./
      dockerfile: decoder.Dockerfile
    ports:
      - "5000:5000"
    links:
      - mongo-db
    environment:
      MONGODB_CONECTION_STRING: mongodb://mongo-db:27017
      PORT: 5000
  mongo-db:
    container_name: mongo-db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=clarity_in_house
    ports:
      - 27017:27017
    volumes:
      - ./mongo-volume:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodb:
